# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "socialapp"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "socialapprender"
    scrape_interval: 15s
    static_configs:
      - targets:
          - socialapp.gomezignacio.com

  - job_name: "cadvisor"
    scrape_interval: 15s
    dns_sd_configs:
      - names:
          - "tasks.cadvisor"
        type: "A"
        port: 8080
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node"
    scrape_interval: 15s
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: "postgres-exporter"
    scrape_interval: 15s
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: "elasticsearch-exporter"
    scrape_interval: 15s
    static_configs:
      - targets:
          - elasticsearch-exporter:9114

  - job_name: "alertmanager"
    scrape_interval: 15s
    static_configs:
      - targets:
          - alertmanager:9093

  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets:
          - prometheus:9090
#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#      port: 9091

#     static_configs:
#          - targets: ['node-exporter:9100']
