/*
Socialapp

Socialapp API for user management, social interactions, authorization, and shortened URL operations.

API version: 1.0.0
Contact: ignacio.gomez.arboleda@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateCommentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCommentRequest{}

// CreateCommentRequest Request payload for creating a comment.
type CreateCommentRequest struct {
	// Text content of the comment.
	Content string `json:"content"`
	// Username of the comment author.
	Username string `json:"username"`
}

type _CreateCommentRequest CreateCommentRequest

// NewCreateCommentRequest instantiates a new CreateCommentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCommentRequest(content string, username string) *CreateCommentRequest {
	this := CreateCommentRequest{}
	this.Content = content
	this.Username = username
	return &this
}

// NewCreateCommentRequestWithDefaults instantiates a new CreateCommentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCommentRequestWithDefaults() *CreateCommentRequest {
	this := CreateCommentRequest{}
	return &this
}

// GetContent returns the Content field value
func (o *CreateCommentRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CreateCommentRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CreateCommentRequest) SetContent(v string) {
	o.Content = v
}

// GetUsername returns the Username field value
func (o *CreateCommentRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateCommentRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateCommentRequest) SetUsername(v string) {
	o.Username = v
}

func (o CreateCommentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCommentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *CreateCommentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCommentRequest := _CreateCommentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCommentRequest)

	if err != nil {
		return err
	}

	*o = CreateCommentRequest(varCreateCommentRequest)

	return err
}

type NullableCreateCommentRequest struct {
	value *CreateCommentRequest
	isSet bool
}

func (v NullableCreateCommentRequest) Get() *CreateCommentRequest {
	return v.value
}

func (v *NullableCreateCommentRequest) Set(val *CreateCommentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCommentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCommentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCommentRequest(val *CreateCommentRequest) *NullableCreateCommentRequest {
	return &NullableCreateCommentRequest{value: val, isSet: true}
}

func (v NullableCreateCommentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCommentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
