# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

services:
  - docker

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  - GO111MODULE=on

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - "1.12.5"

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

jobs:
  include:
    - stage: lint
      script: 
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint # installed in /home/travis/gopath/bin/golangci-lint
      - cd ./bitcoinPrice
      - golangci-lint run       # run a bunch of code checkers/linters in parallel
      cache:
        directories:
          - /home/travis/gopath
    - stage: test
      script:
      - cd ./bitcoinPrice
      - go test -v -race ./...
    - stage: build
      script:
      - cd ./bitcoinPrice
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t igomeza/bitcoinprice:"$TRAVIS_BRANCH"-"$TRAVIS_COMMIT" .
      - docker build -t igomeza/bitcoinprice:latest .
      - docker push igomeza/bitcoinprice:"$TRAVIS_BRANCH"-"$TRAVIS_COMMIT"
      - docker push igomeza/bitcoinprice:latest
    - stage: deploy
      script:
      - mkdir ~/.kube
      - curl -o ~/.kube/config -u $GITHUB_USERNAME:$GITHUb_TOKEN https://gist.githubusercontent.com/$GITHUB_USERNAME/$GIST_ID/raw/$GIST_COMMIT/$GIST_NAME
      - export KUBECONFIG=/home/travis/.kube/config
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - sudo mv ./kubectl /usr/local/bin/kubectl
      - kubectl get pods --insecure-skip-tls-verify
