# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

services:
  - docker

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  - GO111MODULE=on

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - "1.12.5"

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

jobs:
  include:
    - stage: lint
      script: 
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint
      - cd ./bitcoinPrice
      - golangci-lint run       # run a bunch of code checkers/linters in parallel
    - stage: test
      script:
      - cd ./bitcoinPrice
      - go test -v -race ./...
    - stage: build
      script:
      - cd ./bitcoinPrice
      - docker build -t igomeza/bitcoinprice .
