# alertmanager

global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "default-receiver"

receivers:
  - name: "default-receiver"
    webhook_configs:
      - url: http://alertmanager:9093/api/v1/alerts
