global:
  # Also possible to place this URL in a file.
  # Ex: `slack_api_url_file: '/etc/alertmanager/slack_url'`
  slack_api_url_file: "/etc/alertmanager/slack_url"
route:
  receiver: "slack-notifications"
  group_by: [alertname, datacenter, app]

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#notifications"
        text: "http://localhost:3005/alerting/list?ruleType=alerting&alertState=firing&view=list"
