openapi: 3.0.0
info:
  version: "0.0.1"
  title: "Microservices"
servers:
  - url: "localhost:3000"
paths:
  /api/v1/btc:
    get:
      summary: "Sample endpoint: Returns the price of one bitcoin in usd"
      operationId: getBitcoinPrice
      tags:
        - bitcoinprice
        - microservices
      responses:
        "200":
          description: "Sample response: Price of one bitcoin in usd"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BitcoinPrice"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    BitcoinPrice:
      type: object
      required:
        - currency
        - value
      properties:
        currency:
          type: string
        value:
          type: integer
          format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
