openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'Microservices'
servers:
  - url: 'localhost:3000'
  - url: 'https://c54c82e2-7bcc-4743-88af-c57bfdea9ba9.mock.pstmn.io'
paths:
  /api/v1/btc:
    get:
      summary: 'Sample endpoint: Returns the price of one bitcoin in usd'
      operationId: getBitcoinPrice
      tags:
        - bitcoinPrice
        - microservices
      responses:
        '200':
          description: 'Sample response: Price of one bitcoin in usd'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BitcoinPrice'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    BitcoinPrice:
      type: object
      required:
        - currency
        - value
      properties:
        currency:
          type: string
        value:
          type: integer
          format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string