/*
 * Socialapp
 *
 * Socialapp is a generic social network.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
)

// RoleApiController binds http requests to an api service and writes the service results to the http response
type RoleApiController struct {
	service      RoleApiServicer
	errorHandler ErrorHandler
}

// RoleApiOption for how the controller is set up.
type RoleApiOption func(*RoleApiController)

// WithRoleApiErrorHandler inject ErrorHandler into controller
func WithRoleApiErrorHandler(h ErrorHandler) RoleApiOption {
	return func(c *RoleApiController) {
		c.errorHandler = h
	}
}

// NewRoleApiController creates a default api controller
func NewRoleApiController(s RoleApiServicer, opts ...RoleApiOption) Router {
	controller := &RoleApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the RoleApiController
func (c *RoleApiController) Routes() Routes {
	return Routes{
		{
			"AddScopeToRole",
			strings.ToUpper("Post"),
			"/v1/roles/{id}/scopes",
			c.AddScopeToRole,
		},
		{
			"CreateRole",
			strings.ToUpper("Post"),
			"/v1/roles",
			c.CreateRole,
		},
		{
			"DeleteRole",
			strings.ToUpper("Delete"),
			"/v1/roles/{id}",
			c.DeleteRole,
		},
		{
			"GetRole",
			strings.ToUpper("Get"),
			"/v1/roles/{id}",
			c.GetRole,
		},
		{
			"ListRoles",
			strings.ToUpper("Get"),
			"/v1/roles",
			c.ListRoles,
		},
		{
			"ListScopesForRole",
			strings.ToUpper("Get"),
			"/v1/roles/{id}/scopes",
			c.ListScopesForRole,
		},
		{
			"RemoveScopeFromRole",
			strings.ToUpper("Delete"),
			"/v1/roles/{role_id}/scopes/{scope_id}",
			c.RemoveScopeFromRole,
		},
		{
			"UpdateRole",
			strings.ToUpper("Put"),
			"/v1/roles/{id}",
			c.UpdateRole,
		},
	}
}

// AddScopeToRole - Add a scope to a role
func (c *RoleApiController) AddScopeToRole(w http.ResponseWriter, r *http.Request) {
	idParam, err := parseInt32Parameter(chi.URLParam(r, "id"), true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	requestBodyParam := []string{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&requestBodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.AddScopeToRole(r.Context(), idParam, requestBodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// CreateRole - Create a new role
func (c *RoleApiController) CreateRole(w http.ResponseWriter, r *http.Request) {
	roleParam := Role{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&roleParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRoleRequired(roleParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateRole(r.Context(), roleParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// DeleteRole - Delete a role
func (c *RoleApiController) DeleteRole(w http.ResponseWriter, r *http.Request) {
	idParam, err := parseInt32Parameter(chi.URLParam(r, "id"), true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.DeleteRole(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// GetRole - Returns a role
func (c *RoleApiController) GetRole(w http.ResponseWriter, r *http.Request) {
	idParam, err := parseInt32Parameter(chi.URLParam(r, "id"), true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.GetRole(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// ListRoles - Returns a list of roles
func (c *RoleApiController) ListRoles(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	limitParam, err := parseInt32Parameter(query.Get("limit"), false)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	offsetParam, err := parseInt32Parameter(query.Get("offset"), false)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.ListRoles(r.Context(), limitParam, offsetParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// ListScopesForRole - Returns a list of scopes for a role
func (c *RoleApiController) ListScopesForRole(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	idParam, err := parseInt32Parameter(chi.URLParam(r, "id"), true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	limitParam, err := parseInt32Parameter(query.Get("limit"), false)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	offsetParam, err := parseInt32Parameter(query.Get("offset"), false)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.ListScopesForRole(r.Context(), idParam, limitParam, offsetParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// RemoveScopeFromRole - Remove a scope from a role
func (c *RoleApiController) RemoveScopeFromRole(w http.ResponseWriter, r *http.Request) {
	roleIdParam, err := parseInt32Parameter(chi.URLParam(r, "role_id"), true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	scopeIdParam, err := parseInt32Parameter(chi.URLParam(r, "scope_id"), true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.RemoveScopeFromRole(r.Context(), roleIdParam, scopeIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// UpdateRole - Update a role
func (c *RoleApiController) UpdateRole(w http.ResponseWriter, r *http.Request) {
	idParam, err := parseInt32Parameter(chi.URLParam(r, "id"), true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	roleParam := Role{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&roleParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRoleRequired(roleParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateRole(r.Context(), idParam, roleParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}
