/*
 * Socialapp
 *
 * Socialapp is a generic social network.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
)

// URLApiController binds http requests to an api service and writes the service results to the http response
type URLApiController struct {
	service      URLApiServicer
	errorHandler ErrorHandler
}

// URLApiOption for how the controller is set up.
type URLApiOption func(*URLApiController)

// WithURLApiErrorHandler inject ErrorHandler into controller
func WithURLApiErrorHandler(h ErrorHandler) URLApiOption {
	return func(c *URLApiController) {
		c.errorHandler = h
	}
}

// NewURLApiController creates a default api controller
func NewURLApiController(s URLApiServicer, opts ...URLApiOption) Router {
	controller := &URLApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the URLApiController
func (c *URLApiController) Routes() Routes {
	return Routes{
		{
			"CreateUrl",
			strings.ToUpper("Post"),
			"/v1/urls",
			c.CreateUrl,
		},
		{
			"DeleteUrl",
			strings.ToUpper("Delete"),
			"/v1/urls/{alias}",
			c.DeleteUrl,
		},
		{
			"GetUrl",
			strings.ToUpper("Get"),
			"/v1/urls/{alias}",
			c.GetUrl,
		},
		{
			"GetUrlData",
			strings.ToUpper("Get"),
			"/v1/urls/{alias}/data",
			c.GetUrlData,
		},
	}
}

// CreateUrl - Create a new url
func (c *URLApiController) CreateUrl(w http.ResponseWriter, r *http.Request) {
	urlParam := Url{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&urlParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUrlRequired(urlParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateUrl(r.Context(), urlParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// DeleteUrl - Delete a url
func (c *URLApiController) DeleteUrl(w http.ResponseWriter, r *http.Request) {
	aliasParam := chi.URLParam(r, "alias")

	result, err := c.service.DeleteUrl(r.Context(), aliasParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// GetUrl - Get a url
func (c *URLApiController) GetUrl(w http.ResponseWriter, r *http.Request) {
	aliasParam := chi.URLParam(r, "alias")

	result, err := c.service.GetUrl(r.Context(), aliasParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// GetUrlData - Returns a url metadata
func (c *URLApiController) GetUrlData(w http.ResponseWriter, r *http.Request) {
	aliasParam := chi.URLParam(r, "alias")

	result, err := c.service.GetUrlData(r.Context(), aliasParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}
