// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Code    int
	Headers map[string][]string
	Body    interface{}
}
