// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

import (
	"net/http"

	"github.com/go-chi/chi/v5/middleware"
)

func Logger(inner http.Handler) http.Handler {
	return middleware.Logger(inner)
}
