// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

// LikeRequest - Like or unlike a comment.
type LikeRequest struct {

	// Unique identifier of the comment.
	CommentId string `json:"comment_id" validate:"regexp=^-?\\\\d+$"`
}

// AssertLikeRequestRequired checks if the required fields are not zero-ed
func AssertLikeRequestRequired(obj LikeRequest) error {
	elements := map[string]interface{}{
		"comment_id": obj.CommentId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertLikeRequestConstraints checks if the values respects the defined constraints
func AssertLikeRequestConstraints(obj LikeRequest) error {
	return nil
}
