// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

import (
	"encoding/json"
	"fmt"
)

// CreateUserRequest - Request payload for creating a user account.
type CreateUserRequest struct {

	// Unique username for the account.
	Username string `json:"username"`

	// Plain-text password used during account creation.
	Password string `json:"password"`

	// User first name.
	FirstName string `json:"first_name"`

	// User last name.
	LastName string `json:"last_name"`

	// User email address.
	Email string `json:"email"`
}

// UnmarshalJSON validates required property keys then unmarshals into CreateUserRequest
func (o *CreateUserRequest) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"username",
		"password",
		"first_name",
		"last_name",
		"email",
	}

	requiredNullableProperties := map[string]bool{
		"username":   false,
		"password":   false,
		"first_name": false,
		"last_name":  false,
		"email":      false,
	}

	allowedJsonKeys := map[string]struct{}{
		"username":   {},
		"password":   {},
		"first_name": {},
		"last_name":  {},
		"email":      {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded CreateUserRequest

	if value, exists := allProperties["username"]; exists {
		if err = json.Unmarshal(value, &decoded.Username); err != nil {
			return err
		}
	}
	if value, exists := allProperties["password"]; exists {
		if err = json.Unmarshal(value, &decoded.Password); err != nil {
			return err
		}
	}
	if value, exists := allProperties["first_name"]; exists {
		if err = json.Unmarshal(value, &decoded.FirstName); err != nil {
			return err
		}
	}
	if value, exists := allProperties["last_name"]; exists {
		if err = json.Unmarshal(value, &decoded.LastName); err != nil {
			return err
		}
	}
	if value, exists := allProperties["email"]; exists {
		if err = json.Unmarshal(value, &decoded.Email); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertCreateUserRequestRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertCreateUserRequestRequired(obj CreateUserRequest) error {
	return nil
}

// AssertCreateUserRequestConstraints checks if the values respects the defined constraints
func AssertCreateUserRequestConstraints(obj CreateUserRequest) error {
	return nil
}
