/*
 * Socialapp
 *
 * Socialapp is a generic social network.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Scope struct {
	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`

	Description string `json:"description"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}

// AssertScopeRequired checks if the required fields are not zero-ed
func AssertScopeRequired(obj Scope) error {
	elements := map[string]interface{}{
		"name":        obj.Name,
		"description": obj.Description,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertScopeConstraints checks if the values respects the defined constraints
func AssertScopeConstraints(obj Scope) error {
	return nil
}
