// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

// CreateUserRequest - Request payload for creating a user account.
type CreateUserRequest struct {

	// Unique username for the account.
	Username string `json:"username"`

	// Plain-text password used during account creation.
	Password string `json:"password"`

	// User first name.
	FirstName string `json:"first_name"`

	// User last name.
	LastName string `json:"last_name"`

	// User email address.
	Email string `json:"email"`
}

// AssertCreateUserRequestRequired checks if the required fields are not zero-ed
func AssertCreateUserRequestRequired(obj CreateUserRequest) error {
	elements := map[string]interface{}{
		"username":   obj.Username,
		"password":   obj.Password,
		"first_name": obj.FirstName,
		"last_name":  obj.LastName,
		"email":      obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateUserRequestConstraints checks if the values respects the defined constraints
func AssertCreateUserRequestConstraints(obj CreateUserRequest) error {
	return nil
}
