// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

// CreateCommentRequest - Request payload for creating a comment.
type CreateCommentRequest struct {

	// Text content of the comment.
	Content string `json:"content"`

	// Username of the comment author.
	Username string `json:"username"`
}

// AssertCreateCommentRequestRequired checks if the required fields are not zero-ed
func AssertCreateCommentRequestRequired(obj CreateCommentRequest) error {
	elements := map[string]interface{}{
		"content":  obj.Content,
		"username": obj.Username,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateCommentRequestConstraints checks if the values respects the defined constraints
func AssertCreateCommentRequestConstraints(obj CreateCommentRequest) error {
	return nil
}
