// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

import (
	"encoding/json"
	"fmt"
)

// ChangePasswordRequest - Request payload for changing a user's password.
type ChangePasswordRequest struct {

	// Current password.
	OldPassword string `json:"old_password"`

	// New password.
	NewPassword string `json:"new_password"`
}

// UnmarshalJSON validates required property keys then unmarshals into ChangePasswordRequest
func (o *ChangePasswordRequest) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"old_password",
		"new_password",
	}

	requiredNullableProperties := map[string]bool{
		"old_password": false,
		"new_password": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"old_password": {},
		"new_password": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded ChangePasswordRequest

	if value, exists := allProperties["old_password"]; exists {
		if err = json.Unmarshal(value, &decoded.OldPassword); err != nil {
			return err
		}
	}
	if value, exists := allProperties["new_password"]; exists {
		if err = json.Unmarshal(value, &decoded.NewPassword); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertChangePasswordRequestRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertChangePasswordRequestRequired(obj ChangePasswordRequest) error {
	return nil
}

// AssertChangePasswordRequestConstraints checks if the values respects the defined constraints
func AssertChangePasswordRequestConstraints(obj ChangePasswordRequest) error {
	return nil
}
