/*
 * Socialapp
 *
 * Socialapp is a generic social network.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ResetPasswordRequest struct {
	Email string `json:"email"`
}

// AssertResetPasswordRequestRequired checks if the required fields are not zero-ed
func AssertResetPasswordRequestRequired(obj ResetPasswordRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseResetPasswordRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResetPasswordRequest (e.g. [][]ResetPasswordRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResetPasswordRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResetPasswordRequest, ok := obj.(ResetPasswordRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResetPasswordRequestRequired(aResetPasswordRequest)
	})
}
