// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

// AccessToken - OAuth access token response.
type AccessToken struct {

	// Access token used for authenticated requests.
	AccessToken string `json:"access_token"`

	// Type of token returned by the authorization server.
	TokenType string `json:"token_type"`

	// Granted OAuth scopes.
	Scopes []string `json:"scopes,omitempty"`

	// Access token lifetime in seconds.
	ExpiresIn int32 `json:"expires_in"`
}

// AssertAccessTokenRequired checks if the required fields are not zero-ed
func AssertAccessTokenRequired(obj AccessToken) error {
	elements := map[string]interface{}{
		"access_token": obj.AccessToken,
		"token_type":   obj.TokenType,
		"expires_in":   obj.ExpiresIn,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAccessTokenConstraints checks if the values respects the defined constraints
func AssertAccessTokenConstraints(obj AccessToken) error {
	return nil
}
