// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

import (
	"time"
)

// CreateUserResponse - Response payload returned after user creation.
type CreateUserResponse struct {

	// Unique user identifier.
	Id string `json:"id" validate:"regexp=^-?\\\\d+$"`

	// Unique username for the account.
	Username string `json:"username"`

	// User first name.
	FirstName string `json:"first_name"`

	// User last name.
	LastName string `json:"last_name"`

	// User email address.
	Email string `json:"email"`

	// Timestamp when the user was created.
	CreatedAt time.Time `json:"created_at"`
}

// AssertCreateUserResponseRequired checks if the required fields are not zero-ed
func AssertCreateUserResponseRequired(obj CreateUserResponse) error {
	elements := map[string]interface{}{
		"id":         obj.Id,
		"username":   obj.Username,
		"first_name": obj.FirstName,
		"last_name":  obj.LastName,
		"email":      obj.Email,
		"created_at": obj.CreatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateUserResponseConstraints checks if the values respects the defined constraints
func AssertCreateUserResponseConstraints(obj CreateUserResponse) error {
	return nil
}
