// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

import (
	"time"
)

// Url - URL alias and metadata.
type Url struct {

	// Destination URL.
	Url string `json:"url"`

	// Short alias used to reference the URL.
	Alias string `json:"alias"`

	// Timestamp when the alias was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Timestamp when the alias was last updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// Timestamp when the alias was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
}

// AssertUrlRequired checks if the required fields are not zero-ed
func AssertUrlRequired(obj Url) error {
	elements := map[string]interface{}{
		"url":   obj.Url,
		"alias": obj.Alias,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUrlConstraints checks if the values respects the defined constraints
func AssertUrlConstraints(obj Url) error {
	return nil
}
