// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Socialapp
 *
 * Socialapp API for user management, social interactions, authorization, and shortened URL operations.
 *
 * API version: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 */

package openapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// CreateUserResponse - Response payload returned after user creation.
type CreateUserResponse struct {

	// Unique user identifier.
	Id string `json:"id" validate:"regexp=^-?\\d+$"`

	// Unique username for the account.
	Username string `json:"username"`

	// User first name.
	FirstName string `json:"first_name"`

	// User last name.
	LastName string `json:"last_name"`

	// User email address.
	Email string `json:"email"`

	// Timestamp when the user was created.
	CreatedAt time.Time `json:"created_at"`
}

// UnmarshalJSON validates required property keys then unmarshals into CreateUserResponse
func (o *CreateUserResponse) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"id",
		"username",
		"first_name",
		"last_name",
		"email",
		"created_at",
	}

	requiredNullableProperties := map[string]bool{
		"id":         false,
		"username":   false,
		"first_name": false,
		"last_name":  false,
		"email":      false,
		"created_at": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id":         {},
		"username":   {},
		"first_name": {},
		"last_name":  {},
		"email":      {},
		"created_at": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded CreateUserResponse

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["username"]; exists {
		if err = json.Unmarshal(value, &decoded.Username); err != nil {
			return err
		}
	}
	if value, exists := allProperties["first_name"]; exists {
		if err = json.Unmarshal(value, &decoded.FirstName); err != nil {
			return err
		}
	}
	if value, exists := allProperties["last_name"]; exists {
		if err = json.Unmarshal(value, &decoded.LastName); err != nil {
			return err
		}
	}
	if value, exists := allProperties["email"]; exists {
		if err = json.Unmarshal(value, &decoded.Email); err != nil {
			return err
		}
	}
	if value, exists := allProperties["created_at"]; exists {
		if err = json.Unmarshal(value, &decoded.CreatedAt); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertCreateUserResponseRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertCreateUserResponseRequired(obj CreateUserResponse) error {
	return nil
}

// AssertCreateUserResponseConstraints checks if the values respects the defined constraints
func AssertCreateUserResponseConstraints(obj CreateUserResponse) error {
	return nil
}
