version: 2.1
orbs:
  slack: circleci/slack@4.6.2
  jira: circleci/jira@1.3.1
  gcp-gcr: circleci/gcp-gcr@0.15.0
jobs:
  build-bitcoin-service:
    docker:
      - image: cimg/go:1.19
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: bitcoinprice_test

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: git rev-parse HEAD
      - run: cd bitcoinprice &&
          mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: cd bitcoinprice &&
          go mod download &&
          go get github.com/jstemmer/go-junit-report

      - run:
          name: Setup Buffalo
          command: |
            wget https://github.com/gobuffalo/cli/releases/download/v0.18.2/buffalo_0.18.2_Linux_x86_64.tar.gz &&
            tar -xvzf buffalo_0.18.2_Linux_x86_64.tar.gz &&
            sudo mv buffalo /usr/local/bin/buffalo

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            cd bitcoinprice && buffalo test | tee ${TEST_RESULTS}/go-test.out

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

      # slack notifications
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  build-loadgenerator:
    docker:
      - image: docker:17.05.0-ce-git

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker
      - run:
          # Install awscli for deploying image to ecr
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              awscli
            aws --version
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      # Build image
      - run:
          name: Build application Docker image
          command: |
            cd loadgenerator &&
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            cd loadgenerator &&
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      # Push image and update "latest" tag
      - run:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "mainline" ]; then
              login="$(aws ecr get-login)"
              ${login}
              docker tag app "${ECR_ENDPOINT}/loadgenerator:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/loadgenerator:${CIRCLE_SHA1}"

              docker tag app "${ECR_ENDPOINT}/loadgenerator:latest"
              docker push "${ECR_ENDPOINT}/loadgenerator:latest"
            fi
      - run:
          name: Deploy new image in fargate service
          command: |
            if [ "${CIRCLE_BRANCH}" == "mainline" ]; then
              aws ecs update-service --cluster loadgeneratorcluster --service loadgenerator --force-new-deployment --region us-west-2
            fi

  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  send-notification-slack:
    jobs:
      - notify:
          context: slack
  build-workflow:
    jobs:
      - build-bitcoin-service:
          context:
            - slack
            - aws-microservices
          post-steps:
            - jira/notify
      - build-loadgenerator:
          context:
            - slack
            - aws-microservices
