apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: debezium/postgres:15-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: socialapp
          args: ["--wal_level=logical"]
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: db-setup
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-claim
        - name: db-setup
          emptyDir: {}
