CREATE DATABASE urlshortener;
-- SHORTLY
CREATE SEQUENCE IF NOT EXISTS urls_id_seq;
CREATE TABLE IF NOT EXISTS urls (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('urls_id_seq'::regclass),
    url VARCHAR(10000) NOT NULL,
    alias VARCHAR(36) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);
CREATE INDEX IF NOT EXISTS urls_alias_idx ON urls (alias);
