openapi: 3.0.0
info:
  contact:
    email: ignacio.gomez.arboleda@gmail.com
    name: Socialapp
    url: https://socialapp.gomezignacio.com
  description: Socialapp is a generic social network.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Socialapp
  version: 1.0.0
servers:
- url: https://socialapp.gomezignacio.com
- url: http://localhost:8080
- url: http://localhost:8085
security:
- OAuth2: []
tags:
- description: User management
  name: User
- description: Comment management
  name: Comment
- description: Authentication management
  name: Authentication
- description: Following management
  name: Following
- description: Role management
  name: Role
- description: Scope management
  name: Scope
- description: URL management
  name: URL
paths:
  /v1/users:
    get:
      description: List all users in the system (paginated)
      operationId: listUsers
      security:
      - OAuth2:
        - socialapp.users.list
      summary: List users
      tags:
      - User
    post:
      description: Create a new user in the system
      operationId: createUser
      summary: Create user
      tags:
      - User
  /v1/password:
    post:
      description: Change the password of the current user
      operationId: changePassword
      security:
      - OAuth2:
        - socialapp.users.update
      summary: Change password
      tags:
      - User
    put:
      description: Reset the password of a user
      operationId: resetPassword
      security:
      - OAuth2:
        - socialapp.users.update
      summary: Reset password
      tags:
      - User
  /v1/users/{username}/feed:
    get:
      description: Returns a users feed
      operationId: getUserFeed
      security:
      - OAuth2:
        - socialapp.feed.read
      summary: Returns a users feed
      tags:
      - Comment
  /v1/users/{username}/comments:
    get:
      description: Gets all comments for a user
      operationId: getUserComments
      security:
      - OAuth2:
        - socialapp.comments.read
      summary: Gets all comments for a user
      tags:
      - User
      - Comment
  /v1/users/{username}/followers:
    get:
      description: Get all followers for a user
      operationId: getUserFollowers
      security:
      - OAuth2:
        - socialapp.follower.read
      summary: Get all followers for a user
      tags:
      - User
      - Following
  /v1/users/{username}/following:
    get:
      description: Get all followed users for a user (users that the user is following)
      operationId: getFollowingUsers
      security:
      - OAuth2:
        - socialapp.following.list
      summary: Get all followed users for a user
      tags:
      - User
  /v1/users/{followedUsername}/followers/{followerUsername}:
    delete:
      description: Remove a user as a follower of another user
      operationId: unfollowUser
      security:
      - OAuth2:
        - socialapp.follower.delete
      summary: Remove a user as a follower
      tags:
      - User
    post:
      description: Add a user as a follower of another user
      operationId: followUser
      security:
      - OAuth2:
        - socialapp.follower.create
      summary: Add a user as a follower
      tags:
      - User
  /v1/users/{username}:
    delete:
      description: Deletes a particular user by username
      operationId: deleteUser
      security:
      - OAuth2:
        - socialapp.users.delete
      summary: Deletes a particular user
      tags:
      - User
    get:
      description: Get a particular user by username
      operationId: getUserByUsername
      security:
      - OAuth2:
        - socialapp.users.read
      summary: Get a particular user by username
      tags:
      - User
    put:
      description: Update a user by username
      operationId: updateUser
      security:
      - OAuth2:
        - socialapp.users.update
      summary: Update a user
      tags:
      - User
  /v1/users/{username}/roles:
    get:
      description: Get all roles for a user
      operationId: getRolesForUser
      security:
      - OAuth2:
        - socialapp.users.roles.list
      summary: Get all roles for a user
      tags:
      - User
    put:
      description: Update all roles for a user
      operationId: updateRolesForUser
      security:
      - OAuth2:
        - socialapp.users.roles.update
      summary: Update all roles for a user
      tags:
      - User
  /v1/comments/{id}:
    get:
      description: Returns details about a particular comment
      operationId: getComment
      security:
      - OAuth2:
        - socialapp.comments.read
      summary: Returns details about a particular comment
      tags:
      - Comment
  /v1/comments:
    post:
      description: Create a new comment
      operationId: createComment
      security:
      - OAuth2:
        - socialapp.comments.create
      summary: Create a new comment
      tags:
      - Comment
  /v1/oauth/token:
    post:
      description: Get an access token
      operationId: getAccessToken
      security:
      - OAuth2: []
      summary: Get an access token
      tags:
      - Authentication
  /v1/roles:
    get:
      description: Returns a list of roles
      operationId: listRoles
      security:
      - OAuth2:
        - socialapp.roles.list
      summary: Returns a list of roles
      tags:
      - Role
    post:
      description: Create a new role
      operationId: createRole
      security:
      - OAuth2:
        - socialapp.roles.create
      summary: Create a new role
      tags:
      - Role
  /v1/roles/{id}:
    delete:
      description: Delete a role
      operationId: deleteRole
      security:
      - OAuth2:
        - socialapp.roles.delete
      summary: Delete a role
      tags:
      - Role
    get:
      description: Returns a role
      operationId: getRole
      security:
      - OAuth2:
        - socialapp.roles.read
      summary: Returns a role
      tags:
      - Role
    put:
      description: Update a role
      operationId: updateRole
      security:
      - OAuth2:
        - socialapp.roles.update
      summary: Update a role
      tags:
      - Role
  /v1/roles/{id}/scopes:
    get:
      description: Returns a list of scopes for a role
      operationId: listScopesForRole
      security:
      - OAuth2:
        - socialapp.roles.scopes.list
      summary: Returns a list of scopes for a role
      tags:
      - Role
    post:
      description: Add a scope to a role
      operationId: addScopeToRole
      security:
      - OAuth2:
        - socialapp.roles.scopes.create
      summary: Add a scope to a role
      tags:
      - Role
  /v1/roles/{role_id}/scopes/{scope_id}:
    delete:
      description: Remove a scope from a role
      operationId: removeScopeFromRole
      security:
      - OAuth2:
        - socialapp.roles.scopes.delete
      summary: Remove a scope from a role
      tags:
      - Role
  /v1/scopes:
    get:
      description: Returns a list of scopes
      operationId: listScopes
      security:
      - OAuth2:
        - socialapp.scopes.list
      summary: Returns a list of scopes
      tags:
      - Scope
    post:
      description: Create a new scope
      operationId: createScope
      security:
      - OAuth2:
        - socialapp.scopes.create
      summary: Create a new scope
      tags:
      - Scope
  /v1/scopes/{id}:
    delete:
      description: Delete a scope
      operationId: deleteScope
      security:
      - OAuth2:
        - socialapp.scopes.delete
      summary: Delete a scope
      tags:
      - Scope
    get:
      description: Returns a scope
      operationId: getScope
      security:
      - OAuth2:
        - socialapp.scopes.read
      summary: Returns a scope
      tags:
      - Scope
    put:
      description: Update a scope
      operationId: updateScope
      security:
      - OAuth2:
        - socialapp.scopes.update
      summary: Update a scope
      tags:
      - Scope
  /v1/urls/{alias}:
    delete:
      description: Delete a url
      operationId: deleteUrl
      security:
      - OAuth2:
        - shortly.url.delete
      summary: Delete a url
      tags:
      - URL
    get:
      description: Returns a url
      operationId: getUrl
      summary: Get a url
      tags:
      - URL
  /v1/urls/{alias}/data:
    get:
      description: Returns a url
      operationId: getUrlData
      summary: Returns a url metadata
      tags:
      - URL
  /v1/urls:
    post:
      description: Returns a url
      operationId: createUrl
      security:
      - OAuth2:
        - shortly.url.create
      summary: Create a new url
      tags:
      - URL
components:
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            socialapp.users.list: List users
            socialapp.users.create: Create users
            socialapp.users.update: Update users
            socialapp.users.delete: Delete users
            socialapp.users.read: Read a user
            socialapp.comments.list: List comments
            socialapp.comments.create: Create comments
            socialapp.comments.update: Update comments
            socialapp.comments.delete: Delete comments
            socialapp.followers.list: List followers
            socialapp.following.list: List following
            socialapp.roles.list: List roles
            socialapp.roles.create: Create roles
            socialapp.roles.read: Read a role
            socialapp.roles.update: Update roles
            socialapp.roles.delete: Delete roles
            socialapp.scopes.list: List scopes
            socialapp.scopes.create: Create scopes
            socialapp.scopes.read: Read a scope
            socialapp.scopes.update: Update scopes
            socialapp.scopes.delete: Delete scopes
            socialapp.roles.list_scopes: List scopes of a role
            socialapp.roles.scopes.create: Create scopes of a role
            socialapp.roles.scopes.delete: Delete scopes of a role
            socialapp.users.roles.list: List roles of a user
            socialapp.users.roles.create: Create roles of a user
            socialapp.users.roles.update: Update roles of a user
            socialapp.users.roles.delete: Delete roles of a user
            shortly.url.create: Create a url
            shortly.url.update: Update a url
            shortly.url.delete: Delete a url
          tokenUrl: /v1/oauth/token
      type: oauth2
