/*
 * Socialapp
 *
 * Socialapp is a generic social network.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChangePasswordRequest {
    #[serde(rename = "old_password")]
    pub old_password: String,
    #[serde(rename = "new_password")]
    pub new_password: String,
}

impl ChangePasswordRequest {
    pub fn new(old_password: String, new_password: String) -> ChangePasswordRequest {
        ChangePasswordRequest {
            old_password,
            new_password,
        }
    }
}


