/*
 * Socialapp
 *
 * Socialapp is a generic social network.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResetPasswordRequest {
    #[serde(rename = "email")]
    pub email: String,
}

impl ResetPasswordRequest {
    pub fn new(email: String) -> ResetPasswordRequest {
        ResetPasswordRequest {
            email,
        }
    }
}


