apiVersion: 1
datasources:
  - orgId: 1
    version: 1
    name: Elasticsearch
    type: elasticsearch
    access: proxy
  - orgId: 1
    version: 4
    name: GitHub
    type: grafana-github-datasource
    access: proxy
    secureJsonData:
      accessToken: $GITHUB_ACCESSTOKEN
  - orgId: 1
    version: 2
    name: Phlare
    type: phlare
    access: proxy
    url: http://phlare:4100
  - orgId: 1
    version: 8
    name: PostgreSQL
    type: postgres
    access: proxy
    url: database:5432
    user: postgres
    database: socialapp
    jsonData:
      sslmode: disable
    secureJsonData:
      password: $POSTGRESQL_PASSWORD
  - orgId: 1
    version: 2
    name: PostgreSQL-properties
    type: postgres
    access: proxy
    url: database:5432
    user: postgres
    database: puttyknife
    jsonData:
      postgresVersion: 1400
      sslmode: disable
    secureJsonData:
      password: $POSTGRESQL_PROPERTIES_PASSWORD
  - orgId: 1
    version: 1
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: $PROMETHEUS_TLSCACERT
      tlsClientCert: $PROMETHEUS_TLSCLIENTCERT
      tlsClientKey: $PROMETHEUS_TLSCLIENTKEY

allow_embedding: true
auth.anonymous:
  enabled: true
  org_role: Viewer
  org_name: Anonymous
