{
 "title": "Socialapp dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "min_interval",
    "query": "15s, 1m, 5m, 15m, 30m, 1h, 3h, 6h, 12h, 24h"
   },
   {
    "name": "quantile",
    "query": "0.50, 0.75, 0.80, 0.85, 0.90, 0.95, 0.99"
   }
  ]
 },
 "panels": [
  {
   "title": "p90 by handler",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(handler, method, le, code) (rate(http_request_duration_seconds_bucket[$min_interval])))",
     "legendFormat": "{{method}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "New Created Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"id\"\nFROM users\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "4XXs by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"4..\", exported_instance=\"socialapp.gomezignacio.com:443\"}[$min_interval])",
     "legendFormat": "{{code}} {{handler}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(le, handler) (rate(http_request_duration_seconds_bucket{exported_instance=\"socialapp.gomezignacio.com:443\"}[$min_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gandalf time spent in authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile:raw}, sum by(le, auth_result) (rate(authentication_duration_seconds_bucket{exported_instance=\"socialapp.gomezignacio.com:443\"}[$min_interval])))",
     "legendFormat": "{{auth_result}}"
    }
   ]
  },
  {
   "title": "Requests by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(method, handler, code) (rate(http_request_duration_seconds_count[$min_interval]))",
     "legendFormat": "{{method}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Gandalf cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "avg by(status, cache) (rate(gandalf_token_cache[$min_interval]))",
     "legendFormat": "{{cache}} {{status}}"
    }
   ]
  },
  {
   "title": "5XXs by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"5..\", exported_instance=\"socialapp.gomezignacio.com:443\"}[$min_interval])\n\n",
     "legendFormat": "{{code}} {{handler}}"
    }
   ]
  }
 ]
}