{
 "title": "HTTP Service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_interval", "query": "15s, 1m, 5m, 15m, 30m, 1h" },
   {
    "name": "quantile",
    "query": "0.50, 0.75, 0.80, 0.85, 0.90, 0.95, 0.99"
   },
   { "name": "job", "label": "job" }
  ]
 },
 "panels": [
  {
   "title": "WIP new middleware otel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, pattern, status_code) (rate(http_server_response_duration_milliseconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p90 by handler",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(handler, method, le) (rate(http_request_duration_seconds_bucket[$min_interval])))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[30s])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4XXs by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"4..\"}[30s])",
     "legendFormat": "{{code}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(method, handler, code) (rate(http_request_duration_seconds_count[$min_interval]))",
     "legendFormat": "{{method}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Gandalf time spent in authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "gandalf_duration_microseconds{quantile=\"0.75\"}",
     "legendFormat": "{{auth_result}} -  quantile:{{quantile}}"
    }
   ]
  },
  {
   "title": "5XXs by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"5..\"}[30s])",
     "legendFormat": "{{code}} {{handler}}"
    }
   ]
  },
  {
   "title": "Gandalf cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "avg by(status, cache) (rate(gandalf_token_cache[$min_interval]))",
     "legendFormat": "{{cache}} {{status}}"
    }
   ]
  }
 ]
}