{
 "title": "Puttyknife",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Errors Processing Properties",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(error_processing_property[$__rate_interval])",
     "legendFormat": "{{application_name}} {{error}}"
    }
   ]
  },
  {
   "title": "New properties",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', created_at) AS day, COUNT(*)\nFROM properties\nGROUP BY day"
    }
   ]
  },
  {
   "title": "last_seen_at properties",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', last_seen_at) AS day, COUNT(*)\nFROM properties\nGROUP BY day"
    }
   ]
  }
 ]
}