{
 "title": "Socialapp dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_interval", "query": "15s, 1m, 5m, 15m, 30m, 1h" },
   {
    "name": "quantile",
    "query": "0.50, 0.75, 0.80, 0.85, 0.90, 0.95, 0.99"
   }
  ]
 },
 "panels": [
  {
   "title": "p90 by handler",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(handler, method, le) (rate(http_request_duration_seconds_bucket[$min_interval])))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "New Created Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"id\"\nFROM users\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "4XXs by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"4..\"}[30s])",
     "legendFormat": "{{code}} {{handler}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[30s])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gandalf time spent in authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gandalf_duration_seconds_sum[$min_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(method, handler, code) (rate(http_request_duration_seconds_count[$min_interval]))",
     "legendFormat": "{{method}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Gandalf cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "avg by(status, cache) (rate(gandalf_token_cache[$min_interval]))",
     "legendFormat": "{{cache}} {{status}}"
    }
   ]
  },
  {
   "title": "5XXs by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{code=~\"5..\"}[30s])",
     "legendFormat": "{{code}} {{handler}}"
    }
   ]
  }
 ]
}