# Traefik v2 config
# https://doc.traefik.io/traefik/v2.0/
---
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  # websecure:

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: INFO
  format: json

ping:
  entryPoint: "web"

metrics:
  prometheus:
    entryPoint: "web"
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
