# Traefik v2 config
# https://doc.traefik.io/traefik/v2.0/
---
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  weblocal:
    address: ":11111"

certificatesResolvers:
  letsencryptstaging:
    acme:
      email: u393vy+12c8gljgemypk@sharklasers.com
      storage: /letsencrypt/acmestaging.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

  # letsencrypt:
  #   acme:
  #     email: u393vy+12c8gljgemypk@sharklasers.com
  #     storage: /letsencrypt/acme.json
  #     httpChallenge:
  #       # used during the challenge
  #       entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: INFO
  format: json

ping:
  entryPoint: "web"

metrics:
  prometheus:
    entryPoint: "web"
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

tracing:
  serviceName: "traefik"
  addInternals: true
  otlp:
    http:
      endpoint: "http://tempo:4317"

## Dynamic configuration
http:
  serversTransports:
    mytransport:
      disableHTTP2: true
