# Traefik v2 config
# https://doc.traefik.io/traefik/v2.0/
---
api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  webinternal:
    address: ":8081"
  websecureinternal:
    address: ":8443"

certificatesResolvers:
  # letsencryptstaging:
  #   acme:
  #     email: u393vy+12c8gljgemypk@sharklasers.com
  #     storage: /letsencrypt/acmestaging.json
  #     httpChallenge:
  #       # used during the challenge
  #       entryPoint: web
  #     caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

  letsencrypt:
    acme:
      email: u393vy+12c8gljgemypk@sharklasers.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

  letsencrypt-dns:
    acme:
      email: u393vy+12c8gljgemypk@sharklasers.com
      storage: /letsencrypt/acme-dns.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: INFO
  format: json

accessLog:
  filePath: "/tmp/access.log"
  format: common

ping:
  entryPoint: "web"

metrics:
  otlp:
    grpc:
      endpoint: "otel-collector:4317"
      insecure: true

tracing:
  serviceName: "traefik"
  # addInternals: true
  otlp:
    grpc:
      endpoint: "otel-collector:4317"
      insecure: true

## Dynamic configuration
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
  serversTransports:
    mytransport:
      disableHTTP2: true
