package cliflags

const HostFlag = "host"
const UsernameFlag = "username"
const PasswordFlag = "password"
const TokenEndpointFlag = "tokenendpoint"
const PageSizeFlag = "pagesize"
const OffsetFlag = "offset"
const AliasFlag = "alias"
const LongURLFlag = "longurl"
const ShortURLFlag = "shorturl"
const ExpirationFlag = "expiration"
const TagsFlag = "tags"
const PrivateFlag = "private"
const MaxResultsFlag = "maxresults"
const OutputFormatFlag = "outputformat"
const CSVFormat = "csv"
const JSONFormat = "json"
const TableFormat = "table"
const YAMLFormat = "yaml"
const QuietFlag = "quiet"
const YesFlag = "yes"
const NoFlag = "no"
const ForceFlag = "force"
const AllFlag = "all"
const IDFlag = "id"
const NewPasswordFlag = "newpassword"
const NewUsernameFlag = "newusername"
const NewEmailFlag = "newemail"
const NewFullnameFlag = "newfullname"
const RoleFlag = "role"
const ActiveFlag = "active"
const EmailFlag = "email"
const FirstNameFlag = "firstname"
const LastNameFlag = "lastname"
const ScopeFlag = "scope"
const ScopesFlag = "scopes"
const RoleIDFlag = "roleid"
const UserIDFlag = "userid"
const DescriptionFlag = "description"
const ClientNameFlag = "clientname"
const ClientIDFlag = "clientid"
const ClientSecretFlag = "clientsecret"
const RedirectURIsFlag = "redirecturis"
const NameFlag = "name"

// Environment flag
const EnvFlag = "env"

// Environment variable names for CLI configuration
const EnvVarUsername = "SOCIALAPP_CLI_USERNAME"
const EnvVarPassword = "SOCIALAPP_CLI_PASSWORD"
const EnvVarEnvironment = "SOCIALAPP_CLI_ENV"
