apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-claim
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
