export const operations = [
  'welcome',
  'listUsers',
  'createUser',
  'changePassword',
  'resetPassword',
  'getUserFeed',
  'getUserComments',
  'getUserFollowers',
  'getFollowingUsers',
  'unfollowUser',
  'followUser',
  'deleteUser',
  'getUserByUsername',
  'updateUser',
  'getRolesForUser',
  'updateRolesForUser',
  'getComment',
  'createComment',
  'getAccessToken',
  'listRoles',
  'createRole',
  'getRole',
  'updateRole',
  'deleteRole',
  'listScopesForRole',
  'addScopeToRole',
  'removeScopeFromRole',
  'listScopes',
  'createScope',
  'getScope',
  'updateScope',
  'deleteScope',
  'getUrl',
  'deleteUrl',
  'getUrlData',
  'createUrl'
] as const

export type OperationId = (typeof operations)[number]
