/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API welcome message
         * @description Return a welcome message for the Socialapp API.
         */
        get: operations["welcome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description List users with offset-based pagination.
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create user
         * @description Create a new user.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reset password
         * @description Reset a user's password using their email address.
         */
        put: operations["resetPassword"];
        /**
         * Change password
         * @description Change the password for the authenticated user.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user feed
         * @description Return the current user's feed.
         */
        get: operations["getUserFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{username}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List comments for a user
         * @description Get all comments for a specific user.
         */
        get: operations["getUserComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{username}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all followers for a user
         * @description Get all followers for a specific user.
         */
        get: operations["getUserFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{username}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all followed users for a user
         * @description Get all users followed by a specific user.
         */
        get: operations["getFollowingUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{followedUsername}/followers/{followerUsername}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a user as a follower
         * @description Create a follower relationship between two users.
         */
        post: operations["followUser"];
        /**
         * Remove a user as a follower
         * @description Remove a follower relationship between two users.
         */
        delete: operations["unfollowUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a particular user by username
         * @description Get a user by username.
         */
        get: operations["getUserByUsername"];
        /**
         * Update a user
         * @description Update a user by username.
         */
        put: operations["updateUser"];
        post?: never;
        /**
         * Deletes a particular user
         * @description Delete a user by username.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{username}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all roles for a user
         * @description Get all roles assigned to a user.
         */
        get: operations["getRolesForUser"];
        /**
         * Update all roles for a user
         * @description Replace all roles for a user.
         */
        put: operations["updateRolesForUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get comment by ID
         * @description Get details for a specific comment.
         */
        get: operations["getComment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search comments
         * @description Search comments by author and creation time.
         */
        get: operations["searchComments"];
        put?: never;
        /**
         * Create a new comment
         * @description Create a new comment.
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Like a comment
         * @description Like a comment as the authenticated user.
         */
        post: operations["likeComment"];
        /**
         * Unlike a comment
         * @description Remove a like from a comment as the authenticated user.
         */
        delete: operations["unlikeComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get an access token
         * @description Exchange HTTP basic credentials for an access token.
         */
        post: operations["getAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of roles
         * @description List roles with offset-based pagination.
         */
        get: operations["listRoles"];
        put?: never;
        /**
         * Create a new role
         * @description Create a new role.
         */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get role by ID
         * @description Get a role by ID.
         */
        get: operations["getRole"];
        /**
         * Update a role
         * @description Update a role by ID.
         */
        put: operations["updateRole"];
        post?: never;
        /**
         * Delete a role
         * @description Delete a role
         */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles/{id}/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List role scopes
         * @description List scopes assigned to a role.
         */
        get: operations["listScopesForRole"];
        put?: never;
        /**
         * Add a scope to a role
         * @description Add one or more scopes to a role.
         */
        post: operations["addScopeToRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roles/{role_id}/scopes/{scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a scope from a role
         * @description Remove a scope from a role.
         */
        delete: operations["removeScopeFromRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List scopes
         * @description List scopes with offset-based pagination.
         */
        get: operations["listScopes"];
        put?: never;
        /**
         * Create a new scope
         * @description Create a new scope.
         */
        post: operations["createScope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scopes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get scope by ID
         * @description Get a scope by ID.
         */
        get: operations["getScope"];
        /**
         * Update a scope
         * @description Update a scope by ID.
         */
        put: operations["updateScope"];
        post?: never;
        /**
         * Delete a scope
         * @description Delete a scope
         */
        delete: operations["deleteScope"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/urls/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect using URL alias
         * @description Resolve an alias and redirect to the destination URL.
         */
        get: operations["getUrl"];
        put?: never;
        post?: never;
        /**
         * Delete URL alias
         * @description Delete a URL alias and its metadata.
         */
        delete: operations["deleteUrl"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/urls/{alias}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get URL metadata
         * @description Return metadata for a URL alias.
         */
        get: operations["getUrlData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create URL alias
         * @description Create a new URL alias.
         */
        post: operations["createUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Request payload for creating a comment.
         * @example {
         *       "content": "This is a comment",
         *       "username": "johndoe"
         *     }
         */
        CreateCommentRequest: {
            /** @description Text content of the comment. */
            content: string;
            /** @description Username of the comment author. */
            username: string;
        };
        /**
         * @description Request payload for creating a user account.
         * @example {
         *       "username": "johndoe",
         *       "first_name": "John",
         *       "last_name": "Doe",
         *       "password": "Secure123",
         *       "email": "johndoe@mail.com"
         *     }
         */
        CreateUserRequest: {
            /** @description Unique username for the account. */
            username: string;
            /** @description Plain-text password used during account creation. */
            password: string;
            /** @description User first name. */
            first_name: string;
            /** @description User last name. */
            last_name: string;
            /**
             * Format: email
             * @description User email address.
             */
            email: string;
        };
        /**
         * @description Response payload returned after user creation.
         * @example {
         *       "id": 1,
         *       "username": "johndoe",
         *       "first_name": "John",
         *       "last_name": "Doe",
         *       "email": "john@doe.com",
         *       "created_at": "2020-01-01T00:00:00Z"
         *     }
         */
        CreateUserResponse: {
            /**
             * Format: int64
             * @description Unique user identifier.
             */
            id: string;
            /** @description Unique username for the account. */
            username: string;
            /** @description User first name. */
            first_name: string;
            /** @description User last name. */
            last_name: string;
            /**
             * Format: email
             * @description User email address.
             */
            email: string;
            /**
             * Format: date-time
             * @description Timestamp when the user was created.
             */
            created_at: string;
        };
        /**
         * @description User profile information.
         * @example {
         *       "username": "johndoe",
         *       "first_name": "John",
         *       "last_name": "Doe",
         *       "email": "johndoe@mail.com",
         *       "created_at": "2020-01-01T00:00:00Z"
         *     }
         */
        User: {
            /**
             * Format: int64
             * @description Unique user identifier.
             */
            id?: string;
            /** @description Unique username for the account. */
            username: string;
            /** @description User first name. */
            first_name: string;
            /** @description User last name. */
            last_name: string;
            /**
             * Format: email
             * @description User email address.
             */
            email: string;
            /**
             * Format: date-time
             * @description Timestamp when the user was created.
             */
            created_at?: string;
        };
        /**
         * @description User-generated comment.
         * @example {
         *       "content": "This is a comment",
         *       "username": "johndoe"
         *     }
         */
        Comment: {
            /**
             * Format: int64
             * @description Unique comment identifier.
             */
            id?: string;
            /** @description Comment text. */
            content: string;
            /**
             * Format: int64
             * @description Number of likes for the comment.
             */
            like_count?: string;
            /**
             * Format: date-time
             * @description Timestamp when the comment was created.
             */
            created_at?: string;
            /** @description Username of the comment author. */
            username: string;
        };
        /**
         * @description Like or unlike a comment.
         * @example {
         *       "comment_id": 123
         *     }
         */
        LikeRequest: {
            /**
             * Format: int64
             * @description Unique identifier of the comment.
             */
            comment_id: string;
        };
        /**
         * @description OAuth access token response.
         * @example {
         *       "access_token": "123token123",
         *       "token_type": "Bearer",
         *       "expires_in": 3600
         *     }
         */
        AccessToken: {
            /** @description Access token used for authenticated requests. */
            access_token: string;
            /** @description Type of token returned by the authorization server. */
            token_type: string;
            /** @description Granted OAuth scopes. */
            scopes?: string[];
            /** @description Access token lifetime in seconds. */
            expires_in: number;
        };
        /**
         * @description Standard error payload returned by the API.
         * @example {
         *       "code": 404,
         *       "message": "Not found"
         *     }
         */
        Error: {
            /**
             * Format: int32
             * @description HTTP-like error code.
             */
            code: number;
            /** @description Human-readable error message. */
            message: string;
        };
        /**
         * @description Request payload for changing a user's password.
         * @example {
         *       "old_password": "Secure123!",
         *       "new_password": "Secure1234!"
         *     }
         */
        ChangePasswordRequest: {
            /** @description Current password. */
            old_password: string;
            /** @description New password. */
            new_password: string;
        };
        /**
         * @description Request payload for triggering a password reset.
         * @example {
         *       "email": "johndoe@mail.com"
         *     }
         */
        ResetPasswordRequest: {
            /**
             * Format: email
             * @description Email address associated with the user account.
             */
            email: string;
        };
        /**
         * @description Role assigned to users for authorization.
         * @example {
         *       "name": "admin",
         *       "description": "Administrator Role"
         *     }
         */
        Role: {
            /**
             * Format: int64
             * @description Unique role identifier.
             */
            id?: string;
            /** @description Unique role name. */
            name: string;
            /** @description Description of what the role grants. */
            description?: string;
            /**
             * Format: date-time
             * @description Timestamp when the role was created.
             */
            created_at?: string;
        };
        /**
         * @description OAuth scope used for access control.
         * @example {
         *       "name": "socialapp.roles.read",
         *       "description": "Read roles",
         *       "id": 1
         *     }
         */
        Scope: {
            /**
             * Format: int64
             * @description Unique scope identifier.
             */
            id?: string;
            /** @description Scope name (for example, `socialapp.roles.read`). */
            name: string;
            /** @description Description of the permission granted by this scope. */
            description: string;
            /**
             * Format: date-time
             * @description Timestamp when the scope was created.
             */
            created_at?: string;
        };
        /**
         * @description URL alias and metadata.
         * @example {
         *       "alias": "example",
         *       "url": "https://example.com",
         *       "created_at": "2020-01-01T00:00:00Z",
         *       "updated_at": "2020-01-01T00:00:00Z",
         *       "deleted_at": "2020-01-01T00:00:00Z"
         *     }
         */
        URL: {
            /**
             * Format: uri
             * @description Destination URL.
             */
            url: string;
            /** @description Short alias used to reference the URL. */
            alias: string;
            /**
             * Format: date-time
             * @description Timestamp when the alias was created.
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Timestamp when the alias was last updated.
             */
            updated_at?: string;
            /**
             * Format: date-time
             * @description Timestamp when the alias was deleted.
             */
            deleted_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    welcome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Welcome message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example Welcome to the Socialapp API */
                    "text/plain": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": 401,
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": 500,
                     *       "message": "Unexpected error"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of users to return
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description Pagination offset
                 * @example 0
                 */
                offset?: number;
                /**
                 * @description Case-insensitive user search across username, first name, last name, and email
                 * @example john
                 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all the users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 1,
                     *         "username": "johndoe",
                     *         "first_name": "John",
                     *         "last_name": "Doe",
                     *         "email": "johndoe@mail.com",
                     *         "created_at": "2020-01-01T00:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new user */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "username": "johndoe",
                 *       "first_name": "John",
                 *       "last_name": "Doe",
                 *       "password": "Secure123!",
                 *       "email": "johndoe@mail.com"
                 *     }
                 */
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User was created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "username": "johndoe",
                     *       "first_name": "John",
                     *       "last_name": "Doe",
                     *       "email": "johndoe@mail.com",
                     *       "created_at": "2020-01-01T00:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateUserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Reset password */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "johndoe@mail.com"
                 *     }
                 */
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password was reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Change password request */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "old_password": "Secure123!",
                 *       "new_password": "Secure1234!"
                 *     }
                 */
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password was changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUserFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 101,
                     *         "content": "This is a comment",
                     *         "like_count": 10,
                     *         "created_at": "2020-01-01T00:00:00Z",
                     *         "username": "johndoe"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUserComments: {
        parameters: {
            query?: {
                /**
                 * @description How many items to return at one time (max 100)
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description The number of items to skip before starting to collect the result set
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path: {
                /**
                 * @description Username of the user
                 * @example johndoe
                 */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 123,
                     *         "content": "This is a comment",
                     *         "like_count": 3,
                     *         "created_at": "2020-01-01T00:00:00Z",
                     *         "username": "johndoe"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUserFollowers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user
                 * @example johndoe
                 */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User followers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 2,
                     *         "username": "janedoe",
                     *         "first_name": "Jane",
                     *         "last_name": "Doe",
                     *         "email": "janedoe@mail.com",
                     *         "created_at": "2020-01-01T00:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFollowingUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user
                 * @example johndoe
                 */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Followed users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 3,
                     *         "username": "editor1",
                     *         "first_name": "Ed",
                     *         "last_name": "Itor",
                     *         "email": "editor1@mail.com",
                     *         "created_at": "2020-01-01T00:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    followUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user being followed
                 * @example johndoe
                 */
                followedUsername: string;
                /**
                 * @description Username of the follower to add
                 * @example jackdoe
                 */
                followerUsername: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User was followed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    unfollowUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user being followed
                 * @example johndoe
                 */
                followedUsername: string;
                /**
                 * @description Username of the follower to remove
                 * @example jackdoe
                 */
                followerUsername: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User was unfollowed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUserByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user
                 * @example johndoe
                 */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details by username */
            200: {
                headers: {
                    /** @description A link to the next page of responses */
                    "x-next"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Username not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user
                 * @example johndoe
                 */
                username: string;
            };
            cookie?: never;
        };
        /** @description Update a user */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "username": "johndoe",
                 *       "first_name": "John",
                 *       "last_name": "Updated",
                 *       "email": "johndoe@mail.com"
                 *     }
                 */
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description User was updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user
                 * @example johndoe
                 */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User was deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Username not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRolesForUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user
                 * @example johndoe
                 */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles for a user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 1,
                     *         "name": "admin",
                     *         "description": "Administrator role",
                     *         "created_at": "2020-01-01T00:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Role"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateRolesForUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Username of the user
                 * @example johndoe
                 */
                username: string;
            };
            cookie?: never;
        };
        /** @description Update all roles for a user */
        requestBody?: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Roles for a user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ID of the comment
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Details about a comment by ID */
            200: {
                headers: {
                    /** @description A link to the next page of responses */
                    "x-next"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 123,
                     *       "content": "This is a comment",
                     *       "like_count": 10,
                     *       "created_at": "2020-01-01T00:00:00Z",
                     *       "username": "johndoe"
                     *     }
                     */
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchComments: {
        parameters: {
            query?: {
                /** @description Filter comments by the author's username. */
                username?: string;
                /** @description Return comments created at or after this timestamp. */
                start_time?: string;
                /** @description Return comments created at or before this timestamp. */
                end_time?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The most recent matching comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new comment */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "content": "This is a comment",
                 *       "username": "johndoe"
                 *     }
                 */
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description New comment was created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    likeComment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Comment like request */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "comment_id": 123
                 *     }
                 */
                "application/json": components["schemas"]["LikeRequest"];
            };
        };
        responses: {
            /** @description Updated comment with the new like count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    unlikeComment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Comment unlike request */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "comment_id": 123
                 *     }
                 */
                "application/json": components["schemas"]["LikeRequest"];
            };
        };
        responses: {
            /** @description Updated comment with the new like count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "123token123",
                     *       "token_type": "Bearer",
                     *       "scopes": [
                     *         "socialapp.users.list"
                     *       ],
                     *       "expires_in": 3600
                     *     }
                     */
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: {
                /**
                 * @description The numbers of roles to return
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description The number of items to skip before starting to collect the result
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 1,
                     *         "name": "admin",
                     *         "description": "Administrator role",
                     *         "created_at": "2020-01-01T00:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Role"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new role */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "admin",
                 *       "description": "Administrator role"
                 *     }
                 */
                "application/json": components["schemas"]["Role"];
            };
        };
        responses: {
            /** @description New role was created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The id of the role
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "name": "admin",
                     *       "description": "Administrator role",
                     *       "created_at": "2020-01-01T00:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description id of the role
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        /** @description Update a role */
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "name": "admin",
                 *       "description": "Administrator role"
                 *     }
                 */
                "application/json": components["schemas"]["Role"];
            };
        };
        responses: {
            /** @description Role was updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description id of the role
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role was deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listScopesForRole: {
        parameters: {
            query?: {
                /**
                 * @description The numbers of scopes to return
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description The number of items to skip before starting to collect the result
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path: {
                /**
                 * @description The id of the role
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of scopes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 1,
                     *         "name": "socialapp.roles.read",
                     *         "description": "Read role records",
                     *         "created_at": "2020-01-01T00:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Scope"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addScopeToRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The id of the role
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        /** @description Add a scope to a role */
        requestBody: {
            content: {
                /**
                 * @example [
                 *       "socialapp.roles.read",
                 *       "socialapp.roles.update"
                 *     ]
                 */
                "application/json": string[];
            };
        };
        responses: {
            /** @description List of scopes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeScopeFromRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The id of the role
                 * @example 123
                 */
                role_id: string;
                /**
                 * @description The id of the scope
                 * @example 123
                 */
                scope_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope was removed from the role */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listScopes: {
        parameters: {
            query?: {
                /**
                 * @description The numbers of scopes to return
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description The number of items to skip before starting to collect the result
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of scopes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 1,
                     *         "name": "socialapp.roles.read",
                     *         "description": "Read role records",
                     *         "created_at": "2020-01-01T00:00:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Scope"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createScope: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new scope */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "socialapp.roles.read",
                 *       "description": "Read role records"
                 *     }
                 */
                "application/json": components["schemas"]["Scope"];
            };
        };
        responses: {
            /** @description New scope was created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The id of the scope
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "name": "socialapp.roles.read",
                     *       "description": "Read role records",
                     *       "created_at": "2020-01-01T00:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Scope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description id of the scope
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        /** @description Update a scope */
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "name": "socialapp.roles.read",
                 *       "description": "Read role records"
                 *     }
                 */
                "application/json": components["schemas"]["Scope"];
            };
        };
        responses: {
            /** @description Scope was updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description id of the scope
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope was deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The alias of the url
                 * @example abcdef
                 */
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the url */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Redirect to the url */
            308: {
                headers: {
                    /** @description The url */
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Url not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The alias of the url
                 * @example abcdef
                 */
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Url was deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Url not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUrlData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The alias of the url
                 * @example abcdef
                 */
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Url is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["URL"];
                };
            };
            /** @description Url not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create a new url */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "alias": "example",
                 *       "url": "https://example.com"
                 *     }
                 */
                "application/json": components["schemas"]["URL"];
            };
        };
        responses: {
            /** @description Url is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["URL"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Url already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
