services:
  urlshortener:
    container_name: urlshortener
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      [
        "./main",
        "--http-addr=0.0.0.0",
        "--port=8089",
        "--db-url=${DB_URL}",
        "--meta.addr=0.0.0.0",
        "--meta.port=8082",
        "--newrelic-license=${NEWRELIC_LICENSE}",
        "--agent-url=http://otel-collector:4317",
      ]
    ports:
      - "8082:8082"
      - "8089:8089"
    user: "1000:1000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
      restart_policy:
        condition: on-failure
    networks:
      - socialapp_default
    restart: always
    depends_on:
      - setup_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    cpus: 0.5
    mem_limit: 256m
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:53000"
        tag: "urlshortener"

  setup_db:
    image: postgres:15
    container_name: setup_db
    env_file:
      - ./.env
    volumes:
      - ./db/setup:/docker-entrypoint-initdb.d
      - ./init.sh:/init.sh
    ports:
      - "5433:5432"
    networks:
      - socialapp_default
    command: [
        # run ./init.sh to create the database
        "bash",
        "-c",
        "chmod +x /init.sh && /init.sh && sleep 10",
      ]
    restart: "no"
    cpus: 0.5
    mem_limit: 256m
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:53000"
        tag: "setup_db"

networks:
  socialapp_default:
    external: true
