version: "3.8"
services:
  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "./main",
        "--http-addr=0.0.0.0",
        "--port=8089",
        "--db-url=${DB_URL}",
        "--meta.addr=0.0.0.0",
        "--meta.port=8082",
        "--newrelic-license=${NEWRELIC_LICENSE}",
      ]
    ports:
      - "8089:8089"
    user: "1000:1000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
      restart_policy:
        condition: on-failure
    

    networks:
      - socialapp_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    cpus: 0.5
    mem_limit: 256m
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:53000"
        tag: "urlshortener"

networks:
  socialapp_default:
    external: true
