version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}
  db_data: {}
networks:
  front-tier:
  back-tier:


services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: socialapp
    volumes:
      - ./db/setup:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - 3005:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always
