version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}
  db_data: {}
  phlare_data: {}

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: socialapp
    volumes:
      - ./db/setup:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - 3005:3000
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    expose:
      - 9090
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - 9100:9100
  inspector:
    image: ubuntu:latest
    command: sleep infinity

  phlare:
    image: grafana/phlare:latest
    ports:
      - 4100:4100
    volumes:
      - ./phlare/phlare.yml:/etc/phlare/phlare.yml
      - phlare_data:/data
    command:
      - '--config.file=/etc/phlare/phlare.yml'
    expose:
      - 4100
    restart: always
