version: "3.7"

networks:
  elk:
    name: docker-elk_elk

volumes:
  prometheus_data: {}
  grafana_data: {}
  db_data: {}
  phlare_data: {}

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: socialapp
    volumes:
      - ./db/setup:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:51000"
        tag: "database"

  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - 3005:3000
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
      - POSTGRESQL_PROPERTIES_PASSWORD=${POSTGRESQL_PROPERTIES_PASSWORD}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - GITHUB_ACCESSTOKEN=${GITHUB_ACCESSTOKEN}
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
    # send logs to syslog
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:51000"
        tag: "grafana"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--storage.tsdb.retention.size=4GB'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    expose:
      - 9090
    restart: always
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:51000"
        tag: "prometheus"
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - 9093:9093
    expose:
      - 9093
    restart: always
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:51000"
        tag: "alertmanager"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - 9100:9100
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:51000"
        tag: "node-exporter"

  inspector:
    image: ubuntu:latest
    command: sleep infinity
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:51000"
        tag: "inspector"

  phlare:
    image: grafana/phlare:latest
    ports:
      - 4100:4100
    volumes:
      - ./phlare/phlare.yml:/etc/phlare/phlare.yml
      - phlare_data:/data
    command:
      - '--config.file=/etc/phlare/phlare.yml'
    expose:
      - 4100
    restart: always
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:51000"
        tag: "phlare"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    restart: always
    networks:
      - elk
      - default
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:51000"
        tag: "nginx"
