version: "3"
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/setup:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:5433:5432
