version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}
    db_data: {}
networks:
  front-tier:
  back-tier:

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/setup:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:5433:5432
    restart: always
  
  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3005:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always
