// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32        `json:"id"`
	Content   string       `json:"content"`
	LikeCount int32        `json:"likeCount"`
	CreatedAt time.Time    `json:"createdAt"`
	UserID    int32        `json:"userID"`
	DeletedAt sql.NullTime `json:"deletedAt"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	FirstName string       `json:"firstName"`
	LastName  string       `json:"lastName"`
	Email     string       `json:"email"`
	CreatedAt time.Time    `json:"createdAt"`
	DeletedAt sql.NullTime `json:"deletedAt"`
}
