// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, db DBTX, arg CreateCommentParams) (Comment, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, db DBTX, id int32) error
	GetComment(ctx context.Context, db DBTX, id int32) (Comment, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	GetUserByID(ctx context.Context, db DBTX, id int32) (User, error)
	ListComment(ctx context.Context, db DBTX) ([]Comment, error)
	ListUsers(ctx context.Context, db DBTX) ([]User, error)
}

var _ Querier = (*Queries)(nil)
