// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CreateComment = `-- name: CreateComment :execresult
INSERT INTO comments (
  user_id, content
) VALUES (
  ?, ?
)
`

type CreateCommentParams struct {
	UserID  int64  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, db DBTX, arg CreateCommentParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateComment, arg.UserID, arg.Content)
}

const CreateCommentForUser = `-- name: CreateCommentForUser :execresult
INSERT INTO comments (
  user_id, content
) VALUES (
  (SELECT id FROM users WHERE username = ? AND deleted_at IS NULL), ?
)
`

type CreateCommentForUserParams struct {
	Username string `json:"username"`
	Content  string `json:"content"`
}

func (q *Queries) CreateCommentForUser(ctx context.Context, db DBTX, arg CreateCommentForUserParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateCommentForUser, arg.Username, arg.Content)
}

const CreateCredential = `-- name: CreateCredential :execresult
INSERT INTO credentials (
  user_id, public_key, description, name
) VALUES (
  ?, ?, ?, ?
)
`

type CreateCredentialParams struct {
	UserID      int64  `json:"user_id"`
	PublicKey   string `json:"public_key"`
	Description string `json:"description"`
	Name        string `json:"name"`
}

func (q *Queries) CreateCredential(ctx context.Context, db DBTX, arg CreateCredentialParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateCredential,
		arg.UserID,
		arg.PublicKey,
		arg.Description,
		arg.Name,
	)
}

const CreateToken = `-- name: CreateToken :execresult
INSERT INTO tokens (
	token, user_id, valid_until
) VALUES (
  ?, ?, ?
)
`

type CreateTokenParams struct {
	Token      string    `json:"token"`
	UserID     int64     `json:"user_id"`
	ValidUntil time.Time `json:"valid_until"`
}

func (q *Queries) CreateToken(ctx context.Context, db DBTX, arg CreateTokenParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateToken, arg.Token, arg.UserID, arg.ValidUntil)
}

const CreateUser = `-- name: CreateUser :execresult
INSERT INTO users (
    username, hashed_password, salt, first_name, last_name, email, email_token, email_verified_at
) VALUES (
	?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	Username        string       `json:"username"`
	HashedPassword  string       `json:"hashed_password"`
	Salt            string       `json:"salt"`
	FirstName       string       `json:"first_name"`
	LastName        string       `json:"last_name"`
	Email           string       `json:"email"`
	EmailToken      string       `json:"email_token"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateUser,
		arg.Username,
		arg.HashedPassword,
		arg.Salt,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailToken,
		arg.EmailVerifiedAt,
	)
}

const DeleteComment = `-- name: DeleteComment :exec
UPDATE comments
SET deleted_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteComment(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, DeleteComment, id)
	return err
}

const DeleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials
WHERE id = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, DeleteCredential, id)
	return err
}

const DeleteToken = `-- name: DeleteToken :exec
UPDATE tokens
SET valid_until = NOW()
WHERE token = ? AND valid_until IS NULL
`

func (q *Queries) DeleteToken(ctx context.Context, db DBTX, token string) error {
	_, err := db.ExecContext(ctx, DeleteToken, token)
	return err
}

const DeleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, DeleteUser, id)
	return err
}

const DeleteUserByUsername = `-- name: DeleteUserByUsername :exec
UPDATE users
SET deleted_at = NOW()
WHERE username = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, db DBTX, username string) error {
	_, err := db.ExecContext(ctx, DeleteUserByUsername, username)
	return err
}

const FollowUser = `-- name: FollowUser :exec
INSERT INTO followers (
  follower_id, followed_id
) VALUES (
  ?, ?
)
`

type FollowUserParams struct {
	FollowerID int64 `json:"follower_id"`
	FollowedID int64 `json:"followed_id"`
}

func (q *Queries) FollowUser(ctx context.Context, db DBTX, arg FollowUserParams) error {
	_, err := db.ExecContext(ctx, FollowUser, arg.FollowerID, arg.FollowedID)
	return err
}

const GetComment = `-- name: GetComment :one
SELECT id, content, like_count, user_id, created_at, updated_at, deleted_at FROM comments
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, db DBTX, id int64) (Comment, error) {
	row := db.QueryRowContext(ctx, GetComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.LikeCount,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetCredential = `-- name: GetCredential :one
SELECT id, user_id, public_key, description, name, created_at, deleted_at FROM credentials
WHERE public_key = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCredential(ctx context.Context, db DBTX, publicKey string) (Credential, error) {
	row := db.QueryRowContext(ctx, GetCredential, publicKey)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.Description,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetFollowedUsers = `-- name: GetFollowedUsers :many
SELECT
	u.id, u.username, u.hashed_password, u.hashed_password_expires_at, u.salt, u.first_name, u.last_name, u.email, u.email_token, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at
FROM
	users u,
	followers f
WHERE
	f.follower_id = ?
	AND f.followed_id = u.id
	AND u.deleted_at IS NULL
ORDER BY
	u.first_name
`

func (q *Queries) GetFollowedUsers(ctx context.Context, db DBTX, followerID int64) ([]User, error) {
	rows, err := db.QueryContext(ctx, GetFollowedUsers, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.HashedPasswordExpiresAt,
			&i.Salt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailToken,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFollowers = `-- name: GetFollowers :many
SELECT
	u.id, u.username, u.hashed_password, u.hashed_password_expires_at, u.salt, u.first_name, u.last_name, u.email, u.email_token, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at
FROM
	users u,
	followers f
WHERE
	f.followed_id = ?
	AND f.follower_id = u.id
	AND u.deleted_at IS NULL
ORDER BY
	u.first_name
`

func (q *Queries) GetFollowers(ctx context.Context, db DBTX, followedID int64) ([]User, error) {
	rows, err := db.QueryContext(ctx, GetFollowers, followedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.HashedPasswordExpiresAt,
			&i.Salt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailToken,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetToken = `-- name: GetToken :one
SELECT id, user_id, token, valid_from, valid_until FROM tokens
WHERE token = ? LIMIT 1
`

func (q *Queries) GetToken(ctx context.Context, db DBTX, token string) (Token, error) {
	row := db.QueryRowContext(ctx, GetToken, token)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ValidFrom,
		&i.ValidUntil,
	)
	return i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, hashed_password, hashed_password_expires_at, salt, first_name, last_name, email, email_token, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE email = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error) {
	row := db.QueryRowContext(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.HashedPasswordExpiresAt,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailToken,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, username, hashed_password, hashed_password_expires_at, salt, first_name, last_name, email, email_token, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, db DBTX, id int64) (User, error) {
	row := db.QueryRowContext(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.HashedPasswordExpiresAt,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailToken,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, hashed_password, hashed_password_expires_at, salt, first_name, last_name, email, email_token, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE username = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, db DBTX, username string) (User, error) {
	row := db.QueryRowContext(ctx, GetUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.HashedPasswordExpiresAt,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailToken,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserComments = `-- name: GetUserComments :many
SELECT
	c.id, c.content, c.like_count, c.user_id, c.created_at, c.updated_at, c.deleted_at
FROM
	comments c JOIN users u
	ON c.user_id = u.id
WHERE
	u.username = ?
	AND c.deleted_at IS NULL
	AND u.deleted_at IS NULL
ORDER BY
	c.created_at DESC
`

func (q *Queries) GetUserComments(ctx context.Context, db DBTX, username string) ([]Comment, error) {
	rows, err := db.QueryContext(ctx, GetUserComments, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.LikeCount,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListComment = `-- name: ListComment :many
SELECT id, content, like_count, user_id, created_at, updated_at, deleted_at FROM comments
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListComment(ctx context.Context, db DBTX) ([]Comment, error) {
	rows, err := db.QueryContext(ctx, ListComment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.LikeCount,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsers = `-- name: ListUsers :many
SELECT id, username, hashed_password, hashed_password_expires_at, salt, first_name, last_name, email, email_token, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY first_name
`

func (q *Queries) ListUsers(ctx context.Context, db DBTX) ([]User, error) {
	rows, err := db.QueryContext(ctx, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.HashedPasswordExpiresAt,
			&i.Salt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailToken,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UnfollowUser = `-- name: UnfollowUser :exec
DELETE FROM followers
WHERE follower_id = ? AND followed_id = ?
`

type UnfollowUserParams struct {
	FollowerID int64 `json:"follower_id"`
	FollowedID int64 `json:"followed_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, db DBTX, arg UnfollowUserParams) error {
	_, err := db.ExecContext(ctx, UnfollowUser, arg.FollowerID, arg.FollowedID)
	return err
}

const UpdateUser = `-- name: UpdateUser :execresult
UPDATE users 
SET username=?, hashed_password=?, hashed_password_expires_at=?, salt=?, first_name=?, last_name=?, email=?, email_token=?, email_verified_at=?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Username                string       `json:"username"`
	HashedPassword          string       `json:"hashed_password"`
	HashedPasswordExpiresAt time.Time    `json:"hashed_password_expires_at"`
	Salt                    string       `json:"salt"`
	FirstName               string       `json:"first_name"`
	LastName                string       `json:"last_name"`
	Email                   string       `json:"email"`
	EmailToken              string       `json:"email_token"`
	EmailVerifiedAt         sql.NullTime `json:"email_verified_at"`
	ID                      int64        `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (sql.Result, error) {
	return db.ExecContext(ctx, UpdateUser,
		arg.Username,
		arg.HashedPassword,
		arg.HashedPasswordExpiresAt,
		arg.Salt,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailToken,
		arg.EmailVerifiedAt,
		arg.ID,
	)
}

const UpdateUserByUsername = `-- name: UpdateUserByUsername :execresult
UPDATE users 
SET username = ?, hashed_password=?, hashed_password_expires_at=?, salt=?, first_name=?, last_name=?, email=?, email_token=?, email_verified_at=?
WHERE username = ? AND deleted_at IS NULL
`

type UpdateUserByUsernameParams struct {
	NewUsername             string       `json:"new_username"`
	HashedPassword          string       `json:"hashed_password"`
	HashedPasswordExpiresAt time.Time    `json:"hashed_password_expires_at"`
	Salt                    string       `json:"salt"`
	FirstName               string       `json:"first_name"`
	LastName                string       `json:"last_name"`
	Email                   string       `json:"email"`
	EmailToken              string       `json:"email_token"`
	EmailVerifiedAt         sql.NullTime `json:"email_verified_at"`
	OldUsername             string       `json:"old_username"`
}

func (q *Queries) UpdateUserByUsername(ctx context.Context, db DBTX, arg UpdateUserByUsernameParams) (sql.Result, error) {
	return db.ExecContext(ctx, UpdateUserByUsername,
		arg.NewUsername,
		arg.HashedPassword,
		arg.HashedPasswordExpiresAt,
		arg.Salt,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailToken,
		arg.EmailVerifiedAt,
		arg.OldUsername,
	)
}
