// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const CreateComment = `-- name: CreateComment :execresult
INSERT INTO comments (
  user_id, content
) VALUES (
  ?, ?
)
`

type CreateCommentParams struct {
	UserID  int64  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, db DBTX, arg CreateCommentParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateComment, arg.UserID, arg.Content)
}

const CreateCommentForUser = `-- name: CreateCommentForUser :execresult
INSERT INTO comments (
  user_id, content
) VALUES (
  (SELECT id FROM users WHERE username = ? AND deleted_at IS NULL), ?
)
`

type CreateCommentForUserParams struct {
	Username string `json:"username"`
	Content  string `json:"content"`
}

func (q *Queries) CreateCommentForUser(ctx context.Context, db DBTX, arg CreateCommentForUserParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateCommentForUser, arg.Username, arg.Content)
}

const CreateCredential = `-- name: CreateCredential :execresult
INSERT INTO credentials (
  user_id, public_key, description, name
) VALUES (
  ?, ?, ?, ?
)
`

type CreateCredentialParams struct {
	UserID      int64  `json:"user_id"`
	PublicKey   string `json:"public_key"`
	Description string `json:"description"`
	Name        string `json:"name"`
}

func (q *Queries) CreateCredential(ctx context.Context, db DBTX, arg CreateCredentialParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateCredential,
		arg.UserID,
		arg.PublicKey,
		arg.Description,
		arg.Name,
	)
}

const CreateRole = `-- name: CreateRole :execresult
INSERT INTO roles (name, description) 
VALUES (?, ?)
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, db DBTX, arg CreateRoleParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateRole, arg.Name, arg.Description)
}

const CreateRoleScope = `-- name: CreateRoleScope :execresult
INSERT INTO roles_to_scopes (
	role_id, scope_id
) VALUES (
	?, ?
)
`

type CreateRoleScopeParams struct {
	RoleID  int64 `json:"role_id"`
	ScopeID int64 `json:"scope_id"`
}

func (q *Queries) CreateRoleScope(ctx context.Context, db DBTX, arg CreateRoleScopeParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateRoleScope, arg.RoleID, arg.ScopeID)
}

const CreateScope = `-- name: CreateScope :execresult
INSERT INTO scopes (
	  name, description
) VALUES (
  ?, ?
)
`

type CreateScopeParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateScope(ctx context.Context, db DBTX, arg CreateScopeParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateScope, arg.Name, arg.Description)
}

const CreateToken = `-- name: CreateToken :execresult
INSERT INTO tokens (
	token, user_id, valid_until
) VALUES (
  ?, ?, ?
)
`

type CreateTokenParams struct {
	Token      string    `json:"token"`
	UserID     int64     `json:"user_id"`
	ValidUntil time.Time `json:"valid_until"`
}

func (q *Queries) CreateToken(ctx context.Context, db DBTX, arg CreateTokenParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateToken, arg.Token, arg.UserID, arg.ValidUntil)
}

const CreateTokenToScope = `-- name: CreateTokenToScope :execresult
INSERT INTO tokens_to_scopes (
	token_id, scope_id
) VALUES (
  ?, ?
)
`

type CreateTokenToScopeParams struct {
	TokenID int64 `json:"token_id"`
	ScopeID int64 `json:"scope_id"`
}

func (q *Queries) CreateTokenToScope(ctx context.Context, db DBTX, arg CreateTokenToScopeParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateTokenToScope, arg.TokenID, arg.ScopeID)
}

const CreateUser = `-- name: CreateUser :execresult
INSERT INTO users (
    username, hashed_password, salt, first_name, last_name, email, email_token, email_verified_at
) VALUES (
	?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	Username        string       `json:"username"`
	HashedPassword  string       `json:"hashed_password"`
	Salt            string       `json:"salt"`
	FirstName       string       `json:"first_name"`
	LastName        string       `json:"last_name"`
	Email           string       `json:"email"`
	EmailToken      string       `json:"email_token"`
	EmailVerifiedAt sql.NullTime `json:"email_verified_at"`
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateUser,
		arg.Username,
		arg.HashedPassword,
		arg.Salt,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailToken,
		arg.EmailVerifiedAt,
	)
}

const CreateUserToRole = `-- name: CreateUserToRole :execresult
INSERT INTO users_to_roles (
	user_id, role_id
) VALUES (
  ?, ?
)
`

type CreateUserToRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) CreateUserToRole(ctx context.Context, db DBTX, arg CreateUserToRoleParams) (sql.Result, error) {
	return db.ExecContext(ctx, CreateUserToRole, arg.UserID, arg.RoleID)
}

const DeleteAllTokensForUser = `-- name: DeleteAllTokensForUser :exec
UPDATE tokens
SET valid_until = NOW()
WHERE user_id = ? AND NOW() < valid_until
`

func (q *Queries) DeleteAllTokensForUser(ctx context.Context, db DBTX, userID int64) error {
	_, err := db.ExecContext(ctx, DeleteAllTokensForUser, userID)
	return err
}

const DeleteComment = `-- name: DeleteComment :exec
UPDATE comments
SET deleted_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteComment(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, DeleteComment, id)
	return err
}

const DeleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials
WHERE id = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, DeleteCredential, id)
	return err
}

const DeleteRole = `-- name: DeleteRole :exec
UPDATE roles 
SET deleted_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteRole(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, DeleteRole, id)
	return err
}

const DeleteRoleScope = `-- name: DeleteRoleScope :exec
DELETE FROM roles_to_scopes
WHERE role_id = ? AND scope_id = ?
`

type DeleteRoleScopeParams struct {
	RoleID  int64 `json:"role_id"`
	ScopeID int64 `json:"scope_id"`
}

func (q *Queries) DeleteRoleScope(ctx context.Context, db DBTX, arg DeleteRoleScopeParams) error {
	_, err := db.ExecContext(ctx, DeleteRoleScope, arg.RoleID, arg.ScopeID)
	return err
}

const DeleteScope = `-- name: DeleteScope :exec
UPDATE scopes
SET deleted_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteScope(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, DeleteScope, id)
	return err
}

const DeleteToken = `-- name: DeleteToken :exec
UPDATE tokens
SET valid_until = NOW()
WHERE token = ? AND NOW() < valid_until
`

func (q *Queries) DeleteToken(ctx context.Context, db DBTX, token string) error {
	_, err := db.ExecContext(ctx, DeleteToken, token)
	return err
}

const DeleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, DeleteUser, id)
	return err
}

const DeleteUserByUsername = `-- name: DeleteUserByUsername :exec
UPDATE users
SET deleted_at = NOW()
WHERE username = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, db DBTX, username string) error {
	_, err := db.ExecContext(ctx, DeleteUserByUsername, username)
	return err
}

const DeleteUserToRole = `-- name: DeleteUserToRole :exec
DELETE FROM users_to_roles
WHERE user_id = ? AND role_id = ?
`

type DeleteUserToRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) DeleteUserToRole(ctx context.Context, db DBTX, arg DeleteUserToRoleParams) error {
	_, err := db.ExecContext(ctx, DeleteUserToRole, arg.UserID, arg.RoleID)
	return err
}

const FollowUser = `-- name: FollowUser :exec
INSERT INTO followers (
  follower_id, followed_id
) VALUES (
  ?, ?
)
`

type FollowUserParams struct {
	FollowerID int64 `json:"follower_id"`
	FollowedID int64 `json:"followed_id"`
}

func (q *Queries) FollowUser(ctx context.Context, db DBTX, arg FollowUserParams) error {
	_, err := db.ExecContext(ctx, FollowUser, arg.FollowerID, arg.FollowedID)
	return err
}

const GetComment = `-- name: GetComment :one
SELECT id, content, like_count, user_id, created_at, updated_at, deleted_at FROM comments
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, db DBTX, id int64) (Comment, error) {
	row := db.QueryRowContext(ctx, GetComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.LikeCount,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetCredential = `-- name: GetCredential :one
SELECT id, user_id, public_key, description, name, created_at, deleted_at FROM credentials
WHERE public_key = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCredential(ctx context.Context, db DBTX, publicKey string) (Credential, error) {
	row := db.QueryRowContext(ctx, GetCredential, publicKey)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.Description,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetFollowedUsers = `-- name: GetFollowedUsers :many
SELECT
	u.id, u.username, u.hashed_password, u.hashed_password_expires_at, u.salt, u.first_name, u.last_name, u.email, u.email_token, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at
FROM
	users u,
	followers f
WHERE
	f.follower_id = ?
	AND f.followed_id = u.id
	AND u.deleted_at IS NULL
ORDER BY
	u.first_name
`

func (q *Queries) GetFollowedUsers(ctx context.Context, db DBTX, followerID int64) ([]User, error) {
	rows, err := db.QueryContext(ctx, GetFollowedUsers, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.HashedPasswordExpiresAt,
			&i.Salt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailToken,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFollowers = `-- name: GetFollowers :many
SELECT
	u.id, u.username, u.hashed_password, u.hashed_password_expires_at, u.salt, u.first_name, u.last_name, u.email, u.email_token, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at
FROM
	users u,
	followers f
WHERE
	f.followed_id = ?
	AND f.follower_id = u.id
	AND u.deleted_at IS NULL
ORDER BY
	u.first_name
`

func (q *Queries) GetFollowers(ctx context.Context, db DBTX, followedID int64) ([]User, error) {
	rows, err := db.QueryContext(ctx, GetFollowers, followedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.HashedPasswordExpiresAt,
			&i.Salt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailToken,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRole = `-- name: GetRole :one
SELECT id, name, description, created_at, deleted_at FROM roles
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, db DBTX, id int64) (Role, error) {
	row := db.QueryRowContext(ctx, GetRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at, deleted_at FROM roles
WHERE name = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, db DBTX, name string) (Role, error) {
	row := db.QueryRowContext(ctx, GetRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetScope = `-- name: GetScope :one
SELECT id, name, description, created_at, deleted_at FROM scopes
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetScope(ctx context.Context, db DBTX, id int64) (Scope, error) {
	row := db.QueryRowContext(ctx, GetScope, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetScopeByName = `-- name: GetScopeByName :one
SELECT id, name, description, created_at, deleted_at FROM scopes
WHERE name = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetScopeByName(ctx context.Context, db DBTX, name string) (Scope, error) {
	row := db.QueryRowContext(ctx, GetScopeByName, name)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetToken = `-- name: GetToken :one
SELECT id, user_id, token, valid_from, valid_until FROM tokens
WHERE token = ? LIMIT 1
`

func (q *Queries) GetToken(ctx context.Context, db DBTX, token string) (Token, error) {
	row := db.QueryRowContext(ctx, GetToken, token)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ValidFrom,
		&i.ValidUntil,
	)
	return i, err
}

const GetTokenScopes = `-- name: GetTokenScopes :many
SELECT
	s.id, s.name, s.description, s.created_at, s.deleted_at
FROM
	scopes s
	INNER JOIN tokens_to_scopes ts ON ts.scope_id = s.id
	INNER JOIN tokens t ON t.id = ts.token_id
WHERE
	t.id = ?
	AND t.valid_until > NOW()
	AND s.deleted_at IS NULL
`

func (q *Queries) GetTokenScopes(ctx context.Context, db DBTX, id int64) ([]Scope, error) {
	rows, err := db.QueryContext(ctx, GetTokenScopes, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scope
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, hashed_password, hashed_password_expires_at, salt, first_name, last_name, email, email_token, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE email = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error) {
	row := db.QueryRowContext(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.HashedPasswordExpiresAt,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailToken,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, username, hashed_password, hashed_password_expires_at, salt, first_name, last_name, email, email_token, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, db DBTX, id int64) (User, error) {
	row := db.QueryRowContext(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.HashedPasswordExpiresAt,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailToken,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, hashed_password, hashed_password_expires_at, salt, first_name, last_name, email, email_token, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE username = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, db DBTX, username string) (User, error) {
	row := db.QueryRowContext(ctx, GetUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.HashedPasswordExpiresAt,
		&i.Salt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailToken,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserComments = `-- name: GetUserComments :many
SELECT
	c.id, c.content, c.like_count, c.user_id, c.created_at, c.updated_at, c.deleted_at
FROM
	comments c JOIN users u
	ON c.user_id = u.id
WHERE
	u.username = ?
	AND c.deleted_at IS NULL
	AND u.deleted_at IS NULL
ORDER BY
	c.created_at DESC
LIMIT ? OFFSET ?
`

type GetUserCommentsParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetUserComments(ctx context.Context, db DBTX, arg GetUserCommentsParams) ([]Comment, error) {
	rows, err := db.QueryContext(ctx, GetUserComments, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.LikeCount,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRoles = `-- name: GetUserRoles :many
SELECT
	r.id, r.name, r.description, r.created_at, r.deleted_at
FROM
	users u
	INNER JOIN users_to_roles ur ON ur.user_id = u.id
	INNER JOIN roles r ON r.id = ur.role_id
WHERE
	u.id = ?
	AND u.deleted_at IS NULL
	AND r.deleted_at IS NULL
`

func (q *Queries) GetUserRoles(ctx context.Context, db DBTX, id int64) ([]Role, error) {
	rows, err := db.QueryContext(ctx, GetUserRoles, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListComment = `-- name: ListComment :many
SELECT id, content, like_count, user_id, created_at, updated_at, deleted_at FROM comments
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCommentParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListComment(ctx context.Context, db DBTX, arg ListCommentParams) ([]Comment, error) {
	rows, err := db.QueryContext(ctx, ListComment, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.LikeCount,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRoleScopes = `-- name: ListRoleScopes :many
SELECT
	s.id, s.name, s.description, s.created_at, s.deleted_at
FROM
	scopes s
	INNER JOIN roles_to_scopes rs ON rs.scope_id = s.id
	INNER JOIN roles r ON r.id = rs.role_id
WHERE
	r.id = ?
	AND r.deleted_at IS NULL
	AND s.deleted_at IS NULL
ORDER BY
	s.name
LIMIT ? OFFSET ?
`

type ListRoleScopesParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRoleScopes(ctx context.Context, db DBTX, arg ListRoleScopesParams) ([]Scope, error) {
	rows, err := db.QueryContext(ctx, ListRoleScopes, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scope
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRoles = `-- name: ListRoles :many
SELECT id, name, description, created_at, deleted_at FROM roles
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRoles(ctx context.Context, db DBTX, arg ListRolesParams) ([]Role, error) {
	rows, err := db.QueryContext(ctx, ListRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListScopes = `-- name: ListScopes :many
SELECT id, name, description, created_at, deleted_at FROM scopes
WHERE deleted_at IS NULL
LIMIT ? OFFSET ?
`

type ListScopesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListScopes(ctx context.Context, db DBTX, arg ListScopesParams) ([]Scope, error) {
	rows, err := db.QueryContext(ctx, ListScopes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scope
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsers = `-- name: ListUsers :many
SELECT id, username, hashed_password, hashed_password_expires_at, salt, first_name, last_name, email, email_token, email_verified_at, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]User, error) {
	rows, err := db.QueryContext(ctx, ListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.HashedPasswordExpiresAt,
			&i.Salt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailToken,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UnfollowUser = `-- name: UnfollowUser :exec
DELETE FROM followers
WHERE follower_id = ? AND followed_id = ?
`

type UnfollowUserParams struct {
	FollowerID int64 `json:"follower_id"`
	FollowedID int64 `json:"followed_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, db DBTX, arg UnfollowUserParams) error {
	_, err := db.ExecContext(ctx, UnfollowUser, arg.FollowerID, arg.FollowedID)
	return err
}

const UpdateRole = `-- name: UpdateRole :execresult
UPDATE roles 
SET name = ?, description = ? 
WHERE id = ? AND deleted_at IS NULL
`

type UpdateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, db DBTX, arg UpdateRoleParams) (sql.Result, error) {
	return db.ExecContext(ctx, UpdateRole, arg.Name, arg.Description, arg.ID)
}

const UpdateScope = `-- name: UpdateScope :execresult
UPDATE scopes
SET name = ?, description = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateScopeParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateScope(ctx context.Context, db DBTX, arg UpdateScopeParams) (sql.Result, error) {
	return db.ExecContext(ctx, UpdateScope, arg.Name, arg.Description, arg.ID)
}

const UpdateUser = `-- name: UpdateUser :execresult
UPDATE users 
SET username=?, hashed_password=?, hashed_password_expires_at=?, salt=?, first_name=?, last_name=?, email=?, email_token=?, email_verified_at=?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Username                string       `json:"username"`
	HashedPassword          string       `json:"hashed_password"`
	HashedPasswordExpiresAt time.Time    `json:"hashed_password_expires_at"`
	Salt                    string       `json:"salt"`
	FirstName               string       `json:"first_name"`
	LastName                string       `json:"last_name"`
	Email                   string       `json:"email"`
	EmailToken              string       `json:"email_token"`
	EmailVerifiedAt         sql.NullTime `json:"email_verified_at"`
	ID                      int64        `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (sql.Result, error) {
	return db.ExecContext(ctx, UpdateUser,
		arg.Username,
		arg.HashedPassword,
		arg.HashedPasswordExpiresAt,
		arg.Salt,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailToken,
		arg.EmailVerifiedAt,
		arg.ID,
	)
}

const UpdateUserByUsername = `-- name: UpdateUserByUsername :execresult
UPDATE users 
SET username = ?, hashed_password=?, hashed_password_expires_at=?, salt=?, first_name=?, last_name=?, email=?, email_token=?, email_verified_at=?
WHERE username = ? AND deleted_at IS NULL
`

type UpdateUserByUsernameParams struct {
	NewUsername             string       `json:"new_username"`
	HashedPassword          string       `json:"hashed_password"`
	HashedPasswordExpiresAt time.Time    `json:"hashed_password_expires_at"`
	Salt                    string       `json:"salt"`
	FirstName               string       `json:"first_name"`
	LastName                string       `json:"last_name"`
	Email                   string       `json:"email"`
	EmailToken              string       `json:"email_token"`
	EmailVerifiedAt         sql.NullTime `json:"email_verified_at"`
	OldUsername             string       `json:"old_username"`
}

func (q *Queries) UpdateUserByUsername(ctx context.Context, db DBTX, arg UpdateUserByUsernameParams) (sql.Result, error) {
	return db.ExecContext(ctx, UpdateUserByUsername,
		arg.NewUsername,
		arg.HashedPassword,
		arg.HashedPasswordExpiresAt,
		arg.Salt,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailToken,
		arg.EmailVerifiedAt,
		arg.OldUsername,
	)
}
