name: Socialapp SSH and Docker Compose

on:
  push:
    branches:
      - mainline
    paths:
      - "socialapp/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: socialapp/go.sum

      - name: Install Pact CLI
        run: |
          go install github.com/pact-foundation/pact-go/v2@v2.4.2
          pact-go -l DEBUG install --libDir /tmp

      - name: Run unit tests
        run: |
          cd socialapp
          APP_HOST=$APP_HOST make test-ci

      # - name: Run contract tests
      #   run: ./scripts/run-contract-tests.sh

      - name: Run e2e tests
        run: |
          cd socialapp
          make test-e2e

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Make deploy
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          cd socialapp
          make deploy
